name: Setup

inputs:
  python-version:
    required: false
    default: '3.9'
  torch-version:
    required: false
    default: '2.6.0'
  cuda-version:
    required: false
    default: cpu
  torchvision-version:
    required: false
    default: '0.21.0'
  full_install:
    required: false
    default: true

runs:
  using: composite

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python ${{ inputs.python-version }}
      run: |
        uv python install ${{ inputs.python-version }}
        uv venv
        uv pip install --upgrade pip setuptools
      shell: bash

    - name: Install numpy
      run: |
        uv pip install "numpy<2"
      shell: bash

    - name: Install PyTorch ${{ inputs.torch-version }}+${{ inputs.cuda-version }}
      if: ${{ inputs.torch-version != 'nightly' }}
      run: |
        uv pip install torch==${{ inputs.torch-version }} --extra-index-url https://download.pytorch.org/whl/${{ inputs.cuda-version }}
      shell: bash

    - name: Install PyTorch ${{ inputs.torch-version }}+${{ inputs.cuda-version }}
      if: ${{ inputs.torch-version == 'nightly' }}
      run: |
        uv pip install --pre torch --extra-index-url https://download.pytorch.org/whl/nightly/${{ inputs.cuda-version }}
      shell: bash

    - name: Install compatible networkx
      if: ${{ inputs.python-version == '3.9' }}
      run: |
        uv pip install "networkx<3.2"
      shell: bash

    - name: Check installation
      run: |
        uv run --no-project python -c "import torch; print('PyTorch:', torch.__version__)"
        uv run --no-project python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
        uv run --no-project python -c "import torch; print('CUDA:', torch.version.cuda)"
      shell: bash

    - name: Install pyg-lib
      if: ${{ inputs.torch-version != 'nightly' }}
      run: |
        uv pip install --no-index --upgrade pyg-lib -f https://data.pyg.org/whl/nightly/torch-${{ inputs.torch-version }}+${{ inputs.cuda-version }}.html
      shell: bash

    - name: Install faiss-cpu
      if: ${{ inputs.full_install == 'true' && inputs.cuda-version == 'cpu' && runner.os == 'Linux' }}
      run: |
        uv pip install faiss-cpu==1.7.2
      shell: bash

    - name: Install faiss-gpu
      if: ${{ inputs.full_install == 'true' && inputs.cuda-version != 'cpu' && runner.os == 'Linux' }}
      run: |
        uv pip install faiss-gpu==1.7.2
      shell: bash

    - name: Install torchvision
      if: ${{ inputs.full_install == 'true' && inputs.torch-version != 'nightly' }}
      run: |
        uv pip install torchvision==${{ inputs.torchvision-version }} --extra-index-url https://download.pytorch.org/whl/${{ inputs.cuda-version }}
      shell: bash

    - name: Install extension packages
      if: ${{ inputs.full_install == 'true' && inputs.torch-version != 'nightly' }}
      run: |
        uv pip install scipy
        uv pip install --no-index --upgrade torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-${{ inputs.torch-version }}+${{ inputs.cuda-version }}.html
      shell: bash
