package:
  name: pytorch-geometric
  version: 2.3.1

source:
  url: https://files.pythonhosted.org/packages/06/a5/9f5af849c4185da5ea55f70ef17e23f93355cd4e989d82cfc8ba2d8747af/torch_geometric-2.3.1.tar.gz

requirements:
  host:
    - pip
    - python {{ environ.get('PYTHON_VERSION') }}

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
    - psutil
    - tqdm
    - jinja2
    - pyparsing
    - numpy
    - scipy
    - requests
    - scikit-learn

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  number: 1
  script: pip install .

test:
  imports:
    - torch_geometric
    - torch_geometric.nn
    - torch_geometric.data
    - torch_geometric.utils
    - torch_geometric.datasets
    - torch_geometric.transforms

about:
  home: https://github.com/pyg-team/pytorch_geometric
  license: MIT
  summary: Graph Neural Network Library for PyTorch
