package:
  name: pytorch-geometric
  version: 2.6.1

source:
  url: https://files.pythonhosted.org/packages/e8/81/e1b015494cb9e0bf4c47cc8426e49736120248733be0e22072a5628ae9ed/torch_geometric-2.6.1.tar.gz

requirements:
  host:
    - pip
    - flit-core
    - python {{ environ.get('PYTHON_VERSION') }}

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
    - psutil
    - fsspec
    - tqdm
    - jinja2
    - pyparsing
    - numpy
    - scipy
    - aiohttp
    - requests

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  script: pip install .

test:
  imports:
    - torch_geometric
    - torch_geometric.nn
    - torch_geometric.data
    - torch_geometric.utils
    - torch_geometric.datasets
    - torch_geometric.transforms

about:
  home: https://github.com/pyg-team/pytorch_geometric
  license: MIT
  summary: Graph Neural Network Library for PyTorch
