#!/usr/bin/env python
"""Generate requirements/*.txt files from pyproject.toml."""
# based on https://github.com/scikit-image/scikit-image/blob/main/tools/generate_requirements.py

import sys
from pathlib import Path

try:  # standard module since Python 3.11
    import tomllib as toml
except ImportError:
    try:  # available for older Python via pip
        import tomli as toml
    except ImportError:
        sys.exit("Please install `tomli` first: `pip install tomli`")

repo_dir = Path('../')
header = [
    "# Do not edit this file; modify pyproject.toml instead.",
]


def generate_requirement_file(req_list: list[str]) -> None:
    req_fname = Path("requirements.txt")
    req_fname.write_text("\n".join(header + req_list) + "\n")


def main() -> None:
    pyproject = toml.loads((repo_dir / "pyproject.toml").read_text())
    generate_requirement_file(
        pyproject["project"]["optional-dependencies"]['graphgym'])


if __name__ == "__main__":
    main()
